## {{ ansible_managed }}

scrape_configs:
  - job_name: consul
    consul_sd_configs:
      - server: localhost:8500
        datacenter: hl-us-homelab1
        filter: 'ServiceMeta.prometheus_scrape == "true"'
    relabel_configs:
      - action: labelmap
        regex: __meta_(consul_service_metadata_.+)
      - action: labeldrop
        regex: consul_service_metadata_prometheus_scrape
      - source_labels:
          - __meta_consul_dc
        target_label: consul_dc
      - source_labels:
          - __meta_consul_service
        target_label: consul_service
      - source_labels:
          - __meta_consul_node
        target_label: consul_node
